export const FAVORITES_LOADING = "FAVORITES_LOADING";
export const FAVORITES_LOADED = "FAVORITES_LOADED";
export const FAVORITES_ERROR = "FAVORITES_ERROR";

export const ADD_FAVORITE_LOADING = "ADD_FAVORITE_LOADING";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_ERROR = "ADD_FAVORITE_ERROR";

export const REMOVE_FAVORITE_LOADING = "REMOVE_FAVORITE_LOADING";
export const REMOVE_FAVORITE_SUCCESS = "REMOVE_FAVORITE_SUCCESS";
export const REMOVE_FAVORITE_ERROR = "REMOVE_FAVORITE_ERROR";
